export PolySpectral, TaylorSpectral, build_param, build_param!
import ComradeBase: build_param

@doc """
    PolySpectral(index::NTuple{N}, freq0::Number, p0=0.0)
    PolySpectral(index::Number, freq0::Number, p0=0.0)

A frequency-dependent [`DomainParams`](@ref) model that scales a (separately supplied)
base parameter by a polynomial expansion in log-frequency:

    base * exp(∑ₙ index[n] * log(Fr / freq0)^n) + p0

where `Fr` is the observation frequency and `freq0` is the reference frequency. The
base value is *not* stored in `PolySpectral`; it is supplied externally — by
[`MultiDomainParams`](@ref) for image cubes, or by a modifier/`build_param(base, …)`
for geometric models. Evaluated on its own (`build_param(ps, p)` / `ps(p)`),
`PolySpectral` returns the spectral factor `exp(arg) + p0` (i.e. base `1`).

# Arguments
- `index`: polynomial coefficients. An `NTuple{N}` for an order-`N` expansion, or a
  single `Number` for order-1 (a spectral index). Each coefficient may itself be an
  `AbstractArray` for spatially varying coefficients.
- `freq0`: reference frequency. At `Fr = freq0` the spectral factor is `1 + p0`.
- `p0` (optional): additive offset term. Defaults to `0`.

# Examples
```julia
# Geometric modeling: the modifier supplies the base value.
ps = PolySpectral(1.0, 230.0e9)         # spectral index = 1
modify(Gaussian(), Stretch(ps, 1.0))     # frequency-dependent stretch
ps = PolySpectral((1.0, 0.5), 230.0e9)  # order-2: index + curvature

# Imaging: pair a base image with the spectral model via MultiDomainParams (see
# `PolySpectral(base_image, index, freq0)` and `MultiDomainImage`).
```

`TaylorSpectral` is an alias for `PolySpectral` for backwards compatibility.
"""
struct PolySpectral{N, T <: NTuple{N}, F <: Number, P0} <: ComradeBase.FrequencyParams{Any}
    index::T
    freq0::F
    p0::P0

    # Canonical constructor: a tuple of indices defines the expansion order. This is an
    # *inner* constructor on purpose — it suppresses the struct's autogenerated default
    # outer constructor, which has the identical `(NTuple, Number, Any)` signature and
    # would otherwise trigger a "method overwriting" error during precompilation.
    function PolySpectral(index::NTuple{N}, freq0::Number, p0 = 0.0) where {N}
        return new{N, typeof(index), typeof(freq0), typeof(p0)}(index, freq0, p0)
    end
end

# a single spectral index is an order-1 expansion. `p0::Number` is typed so this
# (spectral-only) method strictly wins the all-`Number` 3-argument call over the
# base-supplying convenience constructor `PolySpectral(base, index, freq0, p0)`.
PolySpectral(index::Number, freq0::Number, p0::Number = 0.0) = PolySpectral((index,), freq0, p0)

# spectral model expansion. `x` may be a scalar (single domain point) or an array of
# log-frequencies reshaped along the cube's `Fr` axis (broadcasted cube construction),
# so the powers and products are taken elementwise.
function arg_expand(domain::PolySpectral{N}, p) where {N}
    x = log.(p.Fr ./ domain.freq0)
    return reduce(+, ntuple(n -> domain.index[n] .* x .^ n, Val(N)))
end

# Evaluated on its own (no base): return the spectral factor (base == 1).
function ComradeBase.build_param(domain::PolySpectral, p)
    arg = arg_expand(domain, p)
    return @. exp(arg) + domain.p0
end

# Base supplied externally (image cube via `MultiDomainParams`, or a scalar/array base).
function ComradeBase.build_param(params, domain::PolySpectral, p)
    arg = arg_expand(domain, p)
    return @. params * exp(arg) + domain.p0
end

### MUTATING VERSION (used by the recursive `MultiDomainParams` path) ###

function build_param!(param::AbstractArray, domain::PolySpectral, p)
    arg = arg_expand(domain, p)
    param .= param .* exp.(arg) .+ domain.p0
    return param
end

function build_param!(param::Number, domain::PolySpectral, p)
    arg = arg_expand(domain, p)
    return param * exp(arg) + domain.p0
end

@doc """
    TaylorSpectral

Deprecated alias for [`PolySpectral`](@ref). Use `PolySpectral` instead.
"""
TaylorSpectral
const TaylorSpectral = PolySpectral
